########################################
#### Single Prompt
########################################
list_single_Young_Male = ["Portrait face photo of a young male."]
list_single_Young_Female = ["Portrait face photo of a young female."]
list_single_Aged_Male = ["Portrait face photo of an aged male."]
list_single_Aged_Female = ["Portrait face photo of an aged female."]

########################################
#### Multiply Prompts
#######################################
list_Young_Male = [
    "Portrait face photo of a young male with 5 o'clock shadow, arched eyebrows, and a side profile.",
    "Portrait face photo of a young male with attractive features, bags under his eyes, and a slight tilt to the left.",
    "Portrait face photo of a young male with a bald head, big nose, and intense gaze.",
    "Portrait face photo of a young male with black hair, bushy eyebrows, and a slight downward head pose.",
    "Portrait face photo of a young male with chubby cheeks, double chin, and eyeglasses, looking upwards.",
    "Portrait face photo of a young male with a goatee, brown hair, and a slight smile, looking straight.",
    "Portrait face photo of a young male with grey hair, high cheekbones, and a solemn expression.",
    "Portrait face photo of a young male with heavy makeup, mouth slightly open, and tilted to the right.",
    "Portrait face photo of a young male with a moustache, narrow eyes, and sideburns, in a side profile.",
    "Portrait face photo of a young male with no beard, an oval face, and looking slightly downward.",
    "Portrait face photo of a young male with pale skin, pointy nose, and slightly wavy hair.",
    "Portrait face photo of a young male with a receding hairline, rosy cheeks, and intense gaze.",
    "Portrait face photo of a young male with black hair, wearing a hat, and slight smile, looking left.",
    "Portrait face photo of a young male with wearing a necktie, straight hair, and high cheekbones.",
    "Portrait face photo of a young male with wearing earrings, bushy eyebrows, and head tilted upward.",
    "Portrait face photo of a young male with wearing lipstick, big lips, and looking to the right.",
    "Portrait face photo of a young male with bangs, glasses, and a gentle smile, gazing slightly downward.",
    "Portrait face photo of a young male with a 5 o'clock shadow, strong jawline, and oval face.",
    "Portrait face photo of a young male with big nose, slightly wavy hair, and looking left.",
    "Portrait face photo of a young male with eyeglasses, narrow eyes, and a soft smile, gazing to the side.",
    "Portrait face photo of a young male with bushy eyebrows, no beard, and tilted head.",
    "Portrait face photo of a young male with a goatee, pale skin, and a calm expression, looking slightly up.",
    "Portrait face photo of a young male with grey hair, sideburns, and slightly downturned lips.",
    "Portrait face photo of a young male with attractive facial features, oval face, and a slight head tilt.",
    "Portrait face photo of a young male with pointy nose, narrow eyes, and intense gaze, facing front.",
    "Portrait face photo of a young male with chubby cheeks, receding hairline, and faint smile.",
    "Portrait face photo of a young male with high cheekbones, bushy eyebrows, and strong gaze, looking to the right.",
    "Portrait face photo of a young male with straight hair, heavy makeup, and a soft expression.",
    "Portrait face photo of a young male with pale skin, moustache, and looking slightly upward.",
    "Portrait face photo of a young male with rosy cheeks, oval face, and a slight grin, facing front.",
    "Portrait face photo of a young male with wavy hair, eyeglasses, and an oval face.",
    "Portrait face photo of a young male with high cheekbones, big lips, and slight head tilt to the side.",
    "Portrait face photo of a young male with arched eyebrows, no beard, and looking slightly to the left.",
    "Portrait face photo of a young male with sideburns, mouth slightly open, and a receding hairline.",
    "Portrait face photo of a young male with strong jawline, wearing lipstick, and straight hair.",
    "Portrait face photo of a young male with a goatee, straight eyebrows, and looking slightly down.",
    "Portrait face photo of a young male with black hair, 5 o'clock shadow, and a pointy nose.",
    "Portrait face photo of a young male with rosy cheeks, glasses, and looking to the right.",
    "Portrait face photo of a young male with a narrow chin, bangs, and soft smile.",
    "Portrait face photo of a young male with wearing a hat, bushy eyebrows, and slightly upward head pose.",
    "Portrait face photo of a young male with high cheekbones, straight hair, and slight side profile.",
    "Portrait face photo of a young male with big lips, glasses, and chubby cheeks, gazing left.",
    "Portrait face photo of a young male with big nose, black hair, and a stern look, facing front.",
    "Portrait face photo of a young male with wavy hair, pale skin, and slight downward gaze.",
    "Portrait face photo of a young male with strong jawline, wearing a necktie, and solemn expression.",
    "Portrait face photo of a young male with oval face, wearing earrings, and slight head tilt.",
    "Portrait face photo of a young male with bags under eyes, narrow eyes, and looking upward.",
    "Portrait face photo of a young male with mouth slightly open, wearing lipstick, and a light smile.",
    "Portrait face photo of a young male with wearing a necklace, arched eyebrows, and looking to the side.",
    "Portrait face photo of a young male with rosy cheeks, heavy makeup, and direct gaze."
]
list_Young_Female = [
    "Portrait face photo of a young female with arched eyebrows, rosy cheeks, and a slight smile.",
    "Portrait face photo of a young female with attractive features, big lips, and looking slightly to the left.",
    "Portrait face photo of a young female with bags under eyes, brown hair, and a soft expression.",
    "Portrait face photo of a young female with black hair, high cheekbones, and head tilted to the right.",
    "Portrait face photo of a young female with bangs, wearing lipstick, and looking slightly downwards.",
    "Portrait face photo of a young female with pale skin, narrow eyes, and a gentle smile.",
    "Portrait face photo of a young female with chubby cheeks, arched eyebrows, and gazing to the side.",
    "Portrait face photo of a young female with straight hair, wearing a hat, and head tilted slightly up.",
    "Portrait face photo of a young female with wavy hair, bags under her eyes, and looking to the right.",
    "Portrait face photo of a young female with heavy makeup, mouth slightly open, and gazing slightly downwards.",
    "Portrait face photo of a young female with high cheekbones, wearing earrings, and a slight grin.",
    "Portrait face photo of a young female with an oval face, pale skin, and looking directly forward.",
    "Portrait face photo of a young female with black hair, narrow eyes, and slight smile, gazing to the left.",
    "Portrait face photo of a young female with wearing a necklace, big lips, and a calm expression.",
    "Portrait face photo of a young female with arched eyebrows, high cheekbones, and a gentle gaze.",
    "Portrait face photo of a young female with pale skin, wearing lipstick, and a light smile.",
    "Portrait face photo of a young female with brown hair, rosy cheeks, and head slightly tilted upward.",
    "Portrait face photo of a young female with wearing a hat, chubby cheeks, and looking downward.",
    "Portrait face photo of a young female with wavy hair, arched eyebrows, and a faint smile.",
    "Portrait face photo of a young female with bangs, wearing earrings, and a serious expression.",
    "Portrait face photo of a young female with big lips, bags under eyes, and slight head tilt.",
    "Portrait face photo of a young female with high cheekbones, wearing lipstick, and gazing to the side.",
    "Portrait face photo of a young female with pale skin, narrow chin, and a gentle expression.",
    "Portrait face photo of a young female with straight hair, arched eyebrows, and gazing upwards.",
    "Portrait face photo of a young female with big nose, wavy hair, and looking to the left.",
    "Portrait face photo of a young female with wearing a necktie, oval face, and a slight grin.",
    "Portrait face photo of a young female with straight hair, wearing a hat, and a calm expression.",
    "Portrait face photo of a young female with attractive features, wearing earrings, and gazing forward.",
    "Portrait face photo of a young female with wearing a necklace, narrow eyes, and looking down.",
    "Portrait face photo of a young female with rosy cheeks, wearing lipstick, and a light smile.",
    "Portrait face photo of a young female with bangs, big lips, and head tilted to the right.",
    "Portrait face photo of a young female with chubby cheeks, wearing lipstick, and gazing slightly down.",
    "Portrait face photo of a young female with wearing a hat, narrow eyes, and soft smile.",
    "Portrait face photo of a young female with high cheekbones, straight hair, and slight head tilt.",
    "Portrait face photo of a young female with wavy hair, pale skin, and looking slightly down.",
    "Portrait face photo of a young female with wearing earrings, rosy cheeks, and a big smile.",
    "Portrait face photo of a young female with wearing lipstick, narrow eyes, and calm expression.",
    "Portrait face photo of a young female with black hair, arched eyebrows, and gentle gaze.",
    "Portrait face photo of a young female with chubby cheeks, wearing a necklace, and slight smile.",
    "Portrait face photo of a young female with wearing a hat, wavy hair, and gazing forward.",
    "Portrait face photo of a young female with straight hair, big lips, and soft expression.",
    "Portrait face photo of a young female with wearing lipstick, high cheekbones, and looking to the left.",
    "Portrait face photo of a young female with brown hair, wearing a necktie, and a calm smile.",
    "Portrait face photo of a young female with narrow eyes, arched eyebrows, and a slight frown.",
    "Portrait face photo of a young female with pale skin, wearing earrings, and gazing to the side.",
    "Portrait face photo of a young female with bangs, wearing a hat, and slight smile.",
    "Portrait face photo of a young female with high cheekbones, wearing lipstick, and looking right.",
    "Portrait face photo of a young female with wearing a necklace, pale skin, and soft expression.",
    "Portrait face photo of a young female with attractive features, straight hair, and gazing forward.",
    "Portrait face photo of a young female with wavy hair, rosy cheeks, and slight head tilt."
]
list_Aged_Male = [
    "Portrait face photo of an aged male with 5 o'clock shadow, arched eyebrows, and a slight head tilt.",
    "Portrait face photo of an aged male with bags under eyes, bald head, and looking slightly downward.",
    "Portrait face photo of an aged male with big nose, grey hair, and a solemn expression.",
    "Portrait face photo of an aged male with brown hair, bushy eyebrows, and eyeglasses, looking to the side.",
    "Portrait face photo of an aged male with double chin, rosy cheeks, and head tilted slightly upwards.",
    "Portrait face photo of an aged male with goatee, receding hairline, and a stern look.",
    "Portrait face photo of an aged male with black hair, high cheekbones, and a gentle smile.",
    "Portrait face photo of an aged male with moustache, wearing a hat, and looking to the right.",
    "Portrait face photo of an aged male with eyeglasses, chubby cheeks, and looking slightly to the left.",
    "Portrait face photo of an aged male with pale skin, sideburns, and narrow eyes, in a side profile.",
    "Portrait face photo of an aged male with bags under eyes, grey hair, and a light smile.",
    "Portrait face photo of an aged male with arched eyebrows, big lips, and a slight frown.",
    "Portrait face photo of an aged male with bald head, bushy eyebrows, and direct gaze.",
    "Portrait face photo of an aged male with brown hair, 5 o'clock shadow, and a calm expression.",
    "Portrait face photo of an aged male with heavy makeup, narrow eyes, and looking upward.",
    "Portrait face photo of an aged male with goatee, rosy cheeks, and head tilted downward.",
    "Portrait face photo of an aged male with wearing a necktie, pale skin, and soft smile.",
    "Portrait face photo of an aged male with receding hairline, oval face, and slight smile.",
    "Portrait face photo of an aged male with chubby cheeks, high cheekbones, and straight hair.",
    "Portrait face photo of an aged male with black hair, bags under eyes, and a slight head tilt.",
    "Portrait face photo of an aged male with wearing a hat, bushy eyebrows, and looking downward.",
    "Portrait face photo of an aged male with bald head, eyeglasses, and a slight smile.",
    "Portrait face photo of an aged male with big nose, sideburns, and gentle expression.",
    "Portrait face photo of an aged male with pale skin, oval face, and faint smile.",
    "Portrait face photo of an aged male with wavy hair, high cheekbones, and looking to the left.",
    "Portrait face photo of an aged male with narrow eyes, bags under eyes, and slight downward gaze.",
    "Portrait face photo of an aged male with black hair, big lips, and intense gaze, looking front.",
    "Portrait face photo of an aged male with chubby cheeks, wearing glasses, and slight smile.",
    "Portrait face photo of an aged male with 5 o'clock shadow, high cheekbones, and a slight head tilt.",
    "Portrait face photo of an aged male with big nose, moustache, and looking slightly to the side.",
    "Portrait face photo of an aged male with pale skin, receding hairline, and a calm expression.",
    "Portrait face photo of an aged male with wearing a necktie, double chin, and a light smile.",
    "Portrait face photo of an aged male with rosy cheeks, narrow chin, and looking to the right.",
    "Portrait face photo of an aged male with black hair, wearing a hat, and soft expression.",
    "Portrait face photo of an aged male with bags under eyes, big nose, and an intense look.",
    "Portrait face photo of an aged male with oval face, high cheekbones, and looking slightly down.",
    "Portrait face photo of an aged male with moustache, narrow eyes, and direct gaze.",
    "Portrait face photo of an aged male with big lips, pale skin, and a slight smile.",
    "Portrait face photo of an aged male with bushy eyebrows, chubby cheeks, and looking left.",
    "Portrait face photo of an aged male with wearing earrings, bald head, and gentle expression.",
    "Portrait face photo of an aged male with pale skin, receding hairline, and looking slightly down.",
    "Portrait face photo of an aged male with sideburns, black hair, and intense gaze, looking to the right.",
    "Portrait face photo of an aged male with grey hair, big nose, and looking slightly upward.",
    "Portrait face photo of an aged male with wearing glasses, chubby cheeks, and soft expression.",
    "Portrait face photo of an aged male with bags under eyes, high cheekbones, and a slight frown.",
    "Portrait face photo of an aged male with wearing a necklace, sideburns, and a gentle smile.",
    "Portrait face photo of an aged male with rosy cheeks, heavy makeup, and intense gaze.",
    "Portrait face photo of an aged male with oval face, wearing lipstick, and a calm look.",
    "Portrait face photo of an aged male with brown hair, pale skin, and a soft smile.",
    "Portrait face photo of an aged male with slight 5 o'clock shadow, arched eyebrows, and direct gaze."
]
list_Aged_Female = [
    "Portrait face photo of an aged female with arched eyebrows, grey hair, and a calm expression.",
    "Portrait face photo of an aged female with bags under eyes, high cheekbones, and slight smile.",
    "Portrait face photo of an aged female with attractive features, big lips, and head tilted to the right.",
    "Portrait face photo of an aged female with wearing glasses, chubby cheeks, and gentle smile.",
    "Portrait face photo of an aged female with pale skin, narrow eyes, and looking slightly downward.",
    "Portrait face photo of an aged female with straight hair, wearing a hat, and a calm expression.",
    "Portrait face photo of an aged female with heavy makeup, rosy cheeks, and a slight head tilt.",
    "Portrait face photo of an aged female with grey hair, arched eyebrows, and direct gaze.",
    "Portrait face photo of an aged female with big nose, wearing earrings, and looking to the left.",
    "Portrait face photo of an aged female with high cheekbones, wavy hair, and gentle expression.",
    "Portrait face photo of an aged female with brown hair, bags under her eyes, and slight smile.",
    "Portrait face photo of an aged female with pale skin, mouth slightly open, and head tilted downward.",
    "Portrait face photo of an aged female with wearing lipstick, oval face, and calm smile.",
    "Portrait face photo of an aged female with chubby cheeks, wearing a necktie, and looking slightly up.",
    "Portrait face photo of an aged female with big lips, wearing a hat, and slight frown.",
    "Portrait face photo of an aged female with bushy eyebrows, grey hair, and a solemn expression.",
    "Portrait face photo of an aged female with wearing a necklace, pointy nose, and looking to the side.",
    "Portrait face photo of an aged female with arched eyebrows, narrow chin, and soft expression.",
    "Portrait face photo of an aged female with black hair, rosy cheeks, and slight smile.",
    "Portrait face photo of an aged female with wavy hair, big nose, and gazing slightly to the right.",
    "Portrait face photo of an aged female with wearing earrings, heavy makeup, and intense gaze.",
    "Portrait face photo of an aged female with straight hair, high cheekbones, and looking slightly downward.",
    "Portrait face photo of an aged female with narrow eyes, wearing lipstick, and slight head tilt.",
    "Portrait face photo of an aged female with grey hair, chubby cheeks, and gentle smile.",
    "Portrait face photo of an aged female with big lips, narrow eyes, and a slight frown.",
    "Portrait face photo of an aged female with rosy cheeks, arched eyebrows, and a soft smile.",
    "Portrait face photo of an aged female with wearing a hat, high cheekbones, and gentle gaze.",
    "Portrait face photo of an aged female with wearing a necklace, pale skin, and a slight smile.",
    "Portrait face photo of an aged female with attractive features, wavy hair, and direct gaze.",
    "Portrait face photo of an aged female with oval face, bags under eyes, and looking slightly up.",
    "Portrait face photo of an aged female with wearing a necktie, big lips, and a gentle expression.",
    "Portrait face photo of an aged female with pale skin, narrow eyes, and a calm look.",
    "Portrait face photo of an aged female with chubby cheeks, big nose, and looking slightly to the left.",
    "Portrait face photo of an aged female with straight hair, arched eyebrows, and slight smile.",
    "Portrait face photo of an aged female with wearing lipstick, rosy cheeks, and head tilted slightly down.",
    "Portrait face photo of an aged female with grey hair, narrow chin, and a light smile.",
    "Portrait face photo of an aged female with wearing glasses, big nose, and looking to the right.",
    "Portrait face photo of an aged female with wearing earrings, high cheekbones, and a solemn gaze.",
    "Portrait face photo of an aged female with wavy hair, wearing a hat, and slight grin.",
    "Portrait face photo of an aged female with heavy makeup, straight hair, and direct gaze.",
    "Portrait face photo of an aged female with narrow eyes, wearing lipstick, and a soft expression.",
    "Portrait face photo of an aged female with wearing a necklace, arched eyebrows, and gentle smile.",
    "Portrait face photo of an aged female with pale skin, big lips, and looking slightly down.",
    "Portrait face photo of an aged female with bags under eyes, wearing a necktie, and slight smile.",
    "Portrait face photo of an aged female with wavy hair, high cheekbones, and looking upward.",
    "Portrait face photo of an aged female with wearing earrings, rosy cheeks, and calm gaze.",
    "Portrait face photo of an aged female with straight hair, wearing lipstick, and a slight head tilt.",
    "Portrait face photo of an aged female with attractive features, pale skin, and intense look.",
    "Portrait face photo of an aged female with brown hair, wearing a hat, and soft expression.",
    "Portrait face photo of an aged female with wearing glasses, big nose, and faint smile."
]