########################################
#### Single Prompt
########################################
list_single_Smiling_Young = ["Portrait face photo of a smiling young person."]
list_single_Smiling_Aged = ["Portrait face photo of a smiling aged person."]
list_single_NotSmiling_Young = ["Portrait face photo of a no smiling young person."]
list_single_NotSmiling_Aged = ["Portrait face photo of a no smiling aged person."]

#######################################
### Multiply Prompts
#######################################
list_Smiling_Young = [
    "Portrait face photo of a young smiling person with arched eyebrows, rosy cheeks, and head slightly tilted left.",
    "Portrait face photo of a young smiling person with bangs, high cheekbones, and head turned slightly upward.",
    "Portrait face photo of a young smiling person with brown hair, wearing a necklace, and head facing downward.",
    "Portrait face photo of a young smiling person with black hair, big lips, and head tilted slightly right.",
    "Portrait face photo of a young smiling person with wavy hair, wearing earrings, and head turned slightly to the right.",
    "Portrait face photo of a young smiling person with narrow eyes, chubby cheeks, and head facing slightly upward.",
    "Portrait face photo of a young smiling person with bushy eyebrows, wearing eyeglasses, and head turned slightly left.",
    "Portrait face photo of a young smiling person with straight hair, high cheekbones, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with rosy cheeks, wearing a hat, and head tilted slightly backward.",
    "Portrait face photo of a young smiling person with oval face, big nose, and head slightly tilted to the right.",
    "Portrait face photo of a young smiling person with bangs, wearing lipstick, and head turned slightly to the left.",
    "Portrait face photo of a young smiling person with black hair, arched eyebrows, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with wavy hair, wearing a necktie, and head tilted slightly to the left.",
    "Portrait face photo of a young smiling person with high cheekbones, bags under eyes, and head turned slightly upward.",
    "Portrait face photo of a young smiling person with big lips, wearing earrings, and head tilted slightly forward.",
    "Portrait face photo of a young smiling person with straight hair, narrow eyes, and head turned slightly right.",
    "Portrait face photo of a young smiling person with pale skin, rosy cheeks, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with chubby cheeks, wearing a hat, and head tilted slightly left.",
    "Portrait face photo of a young smiling person with bangs, wearing eyeglasses, and head facing slightly upward.",
    "Portrait face photo of a young smiling person with big nose, arched eyebrows, and head tilted slightly to the right.",
    "Portrait face photo of a young smiling person with wavy hair, wearing a necklace, and head turned slightly left.",
    "Portrait face photo of a young smiling person with high cheekbones, wearing lipstick, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with oval face, bags under eyes, and head tilted slightly forward.",
    "Portrait face photo of a young smiling person with brown hair, big lips, and head turned slightly upward.",
    "Portrait face photo of a young smiling person with black hair, wearing earrings, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with bushy eyebrows, narrow eyes, and head tilted slightly to the left.",
    "Portrait face photo of a young smiling person with straight hair, chubby cheeks, and head turned slightly downward.",
    "Portrait face photo of a young smiling person with bangs, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of a young smiling person with pale skin, wearing lipstick, and head tilted slightly to the right.",
    "Portrait face photo of a young smiling person with high cheekbones, big nose, and head turned slightly forward.",
    "Portrait face photo of a young smiling person with wavy hair, arched eyebrows, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with black hair, wearing eyeglasses, and head tilted slightly left.",
    "Portrait face photo of a young smiling person with big lips, rosy cheeks, and head turned slightly right.",
    "Portrait face photo of a young smiling person with narrow eyes, wearing a necktie, and head facing slightly upward.",
    "Portrait face photo of a young smiling person with chubby cheeks, wearing earrings, and head tilted slightly forward.",
    "Portrait face photo of a young smiling person with bangs, big nose, and head turned slightly to the right.",
    "Portrait face photo of a young smiling person with straight hair, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with pale skin, arched eyebrows, and head tilted slightly to the left.",
    "Portrait face photo of a young smiling person with high cheekbones, wearing lipstick, and head turned slightly upward.",
    "Portrait face photo of a young smiling person with big lips, wearing eyeglasses, and head facing slightly right.",
    "Portrait face photo of a young smiling person with brown hair, rosy cheeks, and head tilted slightly downward.",
    "Portrait face photo of a young smiling person with narrow eyes, big nose, and head turned slightly left.",
    "Portrait face photo of a young smiling person with wavy hair, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of a young smiling person with straight hair, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of a young smiling person with black hair, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of a young smiling person with rosy cheeks, wearing earrings, and head tilted slightly left.",
    "Portrait face photo of a young smiling person with arched eyebrows, big lips, and head turned slightly downward.",
    "Portrait face photo of a young smiling person with bangs, wearing lipstick, and head facing slightly right.",
    "Portrait face photo of a young smiling person with bushy eyebrows, narrow eyes, and head tilted slightly left.",
    "Portrait face photo of a young smiling person with chubby cheeks, high cheekbones, and head turned slightly upward."
]
list_Smiling_Aged = [
    "Portrait face photo of an aged smiling person with grey hair, bags under eyes, and head slightly tilted left.",
    "Portrait face photo of an aged smiling person with arched eyebrows, high cheekbones, and head turned slightly upward.",
    "Portrait face photo of an aged smiling person with bald head, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of an aged smiling person with a 5 o'clock shadow, big nose, and head tilted slightly right.",
    "Portrait face photo of an aged smiling person with bushy eyebrows, wavy hair, and head turned slightly to the right.",
    "Portrait face photo of an aged smiling person with narrow eyes, double chin, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with chubby cheeks, wearing a hat, and head turned slightly left.",
    "Portrait face photo of an aged smiling person with grey hair, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with big lips, rosy cheeks, and head tilted slightly backward.",
    "Portrait face photo of an aged smiling person with oval face, wearing eyeglasses, and head slightly tilted to the right.",
    "Portrait face photo of an aged smiling person with high cheekbones, wearing earrings, and head turned slightly to the left.",
    "Portrait face photo of an aged smiling person with grey hair, narrow eyes, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with black hair, arched eyebrows, and head tilted slightly to the left.",
    "Portrait face photo of an aged smiling person with wavy hair, bags under eyes, and head turned slightly upward.",
    "Portrait face photo of an aged smiling person with rosy cheeks, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of an aged smiling person with chubby face, pointy nose, and head turned slightly to the right.",
    "Portrait face photo of an aged smiling person with oval face, wearing eyeglasses, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with grey hair, high cheekbones, and head turned slightly left.",
    "Portrait face photo of an aged smiling person with bushy eyebrows, wearing a necktie, and head tilted slightly forward.",
    "Portrait face photo of an aged smiling person with straight hair, pale skin, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with big nose, bags under eyes, and head tilted slightly to the right.",
    "Portrait face photo of an aged smiling person with black hair, wearing earrings, and head turned slightly downward.",
    "Portrait face photo of an aged smiling person with narrow eyes, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with wavy hair, double chin, and head tilted slightly left.",
    "Portrait face photo of an aged smiling person with grey hair, wearing lipstick, and head turned slightly upward.",
    "Portrait face photo of an aged smiling person with chubby cheeks, wearing eyeglasses, and head tilted slightly forward.",
    "Portrait face photo of an aged smiling person with bushy eyebrows, wearing a hat, and head turned slightly to the right.",
    "Portrait face photo of an aged smiling person with oval face, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with a goatee, pale skin, and head turned slightly upward.",
    "Portrait face photo of an aged smiling person with arched eyebrows, wearing a necktie, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with straight hair, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of an aged smiling person with narrow eyes, rosy cheeks, and head turned slightly left.",
    "Portrait face photo of an aged smiling person with black hair, wearing lipstick, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with grey hair, wearing earrings, and head tilted slightly to the right.",
    "Portrait face photo of an aged smiling person with big lips, oval face, and head turned slightly downward.",
    "Portrait face photo of an aged smiling person with wavy hair, arched eyebrows, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with black hair, bags under eyes, and head tilted slightly to the left.",
    "Portrait face photo of an aged smiling person with pale skin, wearing eyeglasses, and head turned slightly right.",
    "Portrait face photo of an aged smiling person with chubby cheeks, big nose, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with arched eyebrows, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of an aged smiling person with straight hair, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of an aged smiling person with black hair, wearing lipstick, and head turned slightly to the left.",
    "Portrait face photo of an aged smiling person with narrow eyes, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of an aged smiling person with grey hair, big lips, and head tilted slightly backward.",
    "Portrait face photo of an aged smiling person with oval face, wearing eyeglasses, and head turned slightly upward.",
    "Portrait face photo of an aged smiling person with bushy eyebrows, pale skin, and head facing slightly right.",
    "Portrait face photo of an aged smiling person with high cheekbones, wearing earrings, and head tilted slightly to the left.",
    "Portrait face photo of an aged smiling person with big nose, wearing a necklace, and head turned slightly downward.",
    "Portrait face photo of an aged smiling person with rosy cheeks, wearing a hat, and head facing slightly left.",
    "Portrait face photo of an aged smiling person with grey hair, wearing eyeglasses, and head tilted slightly right."
]
list_NotSmiling_Young = [
    "Portrait face photo of a young person not smiling, with arched eyebrows, big lips, and head slightly tilted left.",
    "Portrait face photo of a young person not smiling, with bangs, high cheekbones, and head turned slightly upward.",
    "Portrait face photo of a young person not smiling, with brown hair, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of a young person not smiling, with narrow eyes, big nose, and head tilted slightly right.",
    "Portrait face photo of a young person not smiling, with bushy eyebrows, wavy hair, and head turned slightly to the right.",
    "Portrait face photo of a young person not smiling, with pale skin, double chin, and head facing slightly upward.",
    "Portrait face photo of a young person not smiling, with straight hair, wearing a hat, and head turned slightly left.",
    "Portrait face photo of a young person not smiling, with chubby cheeks, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with black hair, big lips, and head tilted slightly backward.",
    "Portrait face photo of a young person not smiling, with oval face, wearing a necklace, and head slightly tilted to the right.",
    "Portrait face photo of a young person not smiling, with high cheekbones, wearing earrings, and head turned slightly left.",
    "Portrait face photo of a young person not smiling, with brown hair, narrow eyes, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with black hair, arched eyebrows, and head tilted slightly to the left.",
    "Portrait face photo of a young person not smiling, with wavy hair, bags under eyes, and head turned slightly upward.",
    "Portrait face photo of a young person not smiling, with rosy cheeks, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of a young person not smiling, with big nose, oval face, and head turned slightly to the right.",
    "Portrait face photo of a young person not smiling, with straight hair, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with pale skin, high cheekbones, and head turned slightly left.",
    "Portrait face photo of a young person not smiling, with bushy eyebrows, wearing eyeglasses, and head tilted slightly forward.",
    "Portrait face photo of a young person not smiling, with black hair, big lips, and head facing slightly upward.",
    "Portrait face photo of a young person not smiling, with narrow eyes, wearing a hat, and head tilted slightly to the right.",
    "Portrait face photo of a young person not smiling, with brown hair, double chin, and head turned slightly left.",
    "Portrait face photo of a young person not smiling, with bangs, wearing earrings, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with pale skin, wearing a necktie, and head turned slightly upward.",
    "Portrait face photo of a young person not smiling, with chubby cheeks, wearing lipstick, and head tilted slightly left.",
    "Portrait face photo of a young person not smiling, with black hair, bags under eyes, and head turned slightly downward.",
    "Portrait face photo of a young person not smiling, with wavy hair, oval face, and head facing slightly upward.",
    "Portrait face photo of a young person not smiling, with arched eyebrows, wearing eyeglasses, and head tilted slightly forward.",
    "Portrait face photo of a young person not smiling, with big lips, wearing a hat, and head turned slightly right.",
    "Portrait face photo of a young person not smiling, with high cheekbones, wearing earrings, and head facing slightly left.",
    "Portrait face photo of a young person not smiling, with straight hair, narrow eyes, and head tilted slightly to the right.",
    "Portrait face photo of a young person not smiling, with bushy eyebrows, pale skin, and head turned slightly upward.",
    "Portrait face photo of a young person not smiling, with brown hair, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with narrow eyes, big lips, and head tilted slightly to the left.",
    "Portrait face photo of a young person not smiling, with bangs, wearing a hat, and head turned slightly left.",
    "Portrait face photo of a young person not smiling, with big nose, high cheekbones, and head facing slightly upward.",
    "Portrait face photo of a young person not smiling, with black hair, wearing eyeglasses, and head tilted slightly forward.",
    "Portrait face photo of a young person not smiling, with rosy cheeks, wearing earrings, and head turned slightly to the right.",
    "Portrait face photo of a young person not smiling, with straight hair, chubby cheeks, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with arched eyebrows, oval face, and head tilted slightly upward.",
    "Portrait face photo of a young person not smiling, with big nose, wearing lipstick, and head turned slightly to the left.",
    "Portrait face photo of a young person not smiling, with black hair, wearing a necktie, and head facing slightly right.",
    "Portrait face photo of a young person not smiling, with narrow eyes, bags under eyes, and head tilted slightly forward.",
    "Portrait face photo of a young person not smiling, with straight hair, pale skin, and head turned slightly downward.",
    "Portrait face photo of a young person not smiling, with high cheekbones, wearing earrings, and head facing slightly upward.",
    "Portrait face photo of a young person not smiling, with bangs, wearing a necklace, and head tilted slightly to the right.",
    "Portrait face photo of a young person not smiling, with black hair, chubby cheeks, and head turned slightly to the left.",
    "Portrait face photo of a young person not smiling, with bushy eyebrows, wearing a hat, and head facing slightly downward.",
    "Portrait face photo of a young person not smiling, with rosy cheeks, wearing eyeglasses, and head tilted slightly left.",
    "Portrait face photo of a young person not smiling, with straight hair, narrow eyes, and head turned slightly upward.",
    "Portrait face photo of a young person not smiling, with big lips, wearing earrings, and head facing slightly right."
]
list_NotSmiling_Aged = [
    "Portrait face photo of an aged person not smiling, with grey hair, bags under eyes, and head slightly tilted left.",
    "Portrait face photo of an aged person not smiling, with arched eyebrows, high cheekbones, and head turned slightly upward.",
    "Portrait face photo of an aged person not smiling, with bald head, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of an aged person not smiling, with a 5 o'clock shadow, big nose, and head tilted slightly right.",
    "Portrait face photo of an aged person not smiling, with bushy eyebrows, wavy hair, and head turned slightly to the right.",
    "Portrait face photo of an aged person not smiling, with narrow eyes, double chin, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with chubby cheeks, wearing a hat, and head turned slightly left.",
    "Portrait face photo of an aged person not smiling, with grey hair, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with big lips, pale skin, and head tilted slightly backward.",
    "Portrait face photo of an aged person not smiling, with oval face, wearing eyeglasses, and head slightly tilted to the right.",
    "Portrait face photo of an aged person not smiling, with high cheekbones, wearing earrings, and head turned slightly to the left.",
    "Portrait face photo of an aged person not smiling, with grey hair, narrow eyes, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with black hair, arched eyebrows, and head tilted slightly to the left.",
    "Portrait face photo of an aged person not smiling, with wavy hair, bags under eyes, and head turned slightly upward.",
    "Portrait face photo of an aged person not smiling, with rosy cheeks, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of an aged person not smiling, with chubby face, pointy nose, and head turned slightly to the right.",
    "Portrait face photo of an aged person not smiling, with oval face, wearing eyeglasses, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with grey hair, high cheekbones, and head turned slightly left.",
    "Portrait face photo of an aged person not smiling, with bushy eyebrows, wearing a necktie, and head tilted slightly forward.",
    "Portrait face photo of an aged person not smiling, with straight hair, pale skin, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with big nose, bags under eyes, and head tilted slightly to the right.",
    "Portrait face photo of an aged person not smiling, with black hair, wearing earrings, and head turned slightly downward.",
    "Portrait face photo of an aged person not smiling, with narrow eyes, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with wavy hair, double chin, and head tilted slightly left.",
    "Portrait face photo of an aged person not smiling, with grey hair, wearing lipstick, and head turned slightly upward.",
    "Portrait face photo of an aged person not smiling, with chubby cheeks, wearing eyeglasses, and head tilted slightly forward.",
    "Portrait face photo of an aged person not smiling, with bushy eyebrows, wearing a hat, and head turned slightly to the right.",
    "Portrait face photo of an aged person not smiling, with oval face, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with a goatee, pale skin, and head turned slightly upward.",
    "Portrait face photo of an aged person not smiling, with arched eyebrows, wearing a necktie, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with straight hair, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of an aged person not smiling, with narrow eyes, rosy cheeks, and head turned slightly left.",
    "Portrait face photo of an aged person not smiling, with black hair, wearing lipstick, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with grey hair, wearing earrings, and head tilted slightly to the right.",
    "Portrait face photo of an aged person not smiling, with big lips, oval face, and head turned slightly downward.",
    "Portrait face photo of an aged person not smiling, with wavy hair, arched eyebrows, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with black hair, bags under eyes, and head tilted slightly to the left.",
    "Portrait face photo of an aged person not smiling, with pale skin, wearing eyeglasses, and head turned slightly right.",
    "Portrait face photo of an aged person not smiling, with chubby cheeks, big nose, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with arched eyebrows, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of an aged person not smiling, with straight hair, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of an aged person not smiling, with black hair, wearing lipstick, and head turned slightly to the left.",
    "Portrait face photo of an aged person not smiling, with narrow eyes, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of an aged person not smiling, with grey hair, big lips, and head tilted slightly backward.",
    "Portrait face photo of an aged person not smiling, with oval face, wearing eyeglasses, and head turned slightly upward.",
    "Portrait face photo of an aged person not smiling, with bushy eyebrows, pale skin, and head facing slightly right.",
    "Portrait face photo of an aged person not smiling, with high cheekbones, wearing earrings, and head tilted slightly to the left.",
    "Portrait face photo of an aged person not smiling, with big nose, wearing a necklace, and head turned slightly downward.",
    "Portrait face photo of an aged person not smiling, with rosy cheeks, wearing a hat, and head facing slightly left.",
    "Portrait face photo of an aged person not smiling, with grey hair, wearing eyeglasses, and head tilted slightly right."
]