########################################
#### Single Prompt
########################################
list_single_Smiling_Male = ["Portrait face photo of a smiling male."]
list_single_Smiling_Female = ["Portrait face photo of a smiling female."]
list_single_NoSmiling_Male = ["Portrait face photo of a no-smiling male."]
list_single_NoSmiling_Female = ["Portrait face photo of a no-smiling female."]

########################################
#### Multiply Prompts
########################################
list_Smiling_Male = [
    "Portrait face photo of a smiling male with a 5 o'clock shadow, high cheekbones, and head slightly tilted left.",
    "Portrait face photo of a smiling male with arched eyebrows, chubby cheeks, and head turned slightly upward.",
    "Portrait face photo of a smiling male with a receding hairline, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of a smiling male with big lips, narrow eyes, slight double chin, head tilted right.",
    "Portrait face photo of a smiling male with black hair, a goatee, and head turned slightly right.",
    "Portrait face photo of a smiling male with grey hair, an oval face, and head facing slightly upward.",
    "Portrait face photo of a smiling male with bushy eyebrows, bags under eyes, and head turned slightly left.",
    "Portrait face photo of a smiling male with brown hair, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of a smiling male with a moustache, high cheekbones, and head tilted slightly backward.",
    "Portrait face photo of a smiling male with a bald head, pointy nose, and head slightly turned to the right.",
    "Portrait face photo of a smiling male with a goatee, big nose, and head tilted slightly forward.",
    "Portrait face photo of a smiling male with wavy hair, wearing earrings, and head turned slightly left.",
    "Portrait face photo of a smiling male with a 5 o'clock shadow, arched eyebrows, and head turned to the right.",
    "Portrait face photo of a smiling male with a narrow nose, slight double chin, and head facing upward.",
    "Portrait face photo of a smiling male with big lips, wearing a hat, and head tilted slightly to the left.",
    "Portrait face photo of a smiling male with a chubby face, straight hair, and head turned slightly downward.",
    "Portrait face photo of a smiling male with a goatee, pale skin, and head tilted slightly right.",
    "Portrait face photo of a smiling male with bags under eyes, wearing a necktie, and head turned slightly upward.",
    "Portrait face photo of a smiling male with wavy hair, arched eyebrows, and head slightly tilted forward.",
    "Portrait face photo of a smiling male with a receding hairline, pointy nose, and head facing slightly downward.",
    "Portrait face photo of a smiling male with a big nose, wearing eyeglasses, and head tilted slightly left.",
    "Portrait face photo of a smiling male with grey hair, high cheekbones, and head turned slightly to the left.",
    "Portrait face photo of a smiling male with bushy eyebrows, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of a smiling male with chubby cheeks, oval face, and head turned slightly upward.",
    "Portrait face photo of a smiling male with a double chin, straight hair, and head facing slightly left.",
    "Portrait face photo of a smiling male with big lips, wearing earrings, and head tilted slightly backward.",
    "Portrait face photo of a smiling male with a moustache, bags under eyes, and head turned slightly to the right.",
    "Portrait face photo of a smiling male with black hair, wearing a necktie, and head facing downward.",
    "Portrait face photo of a smiling male with big nose, arched eyebrows, and head turned slightly left.",
    "Portrait face photo of a smiling male with wavy hair, wearing lipstick, and head tilted slightly right.",
    "Portrait face photo of a smiling male with bushy eyebrows, pale skin, and head turned slightly upward.",
    "Portrait face photo of a smiling male with brown hair, high cheekbones, and head tilted slightly downward.",
    "Portrait face photo of a smiling male with arched eyebrows, wearing a hat, and head turned slightly left.",
    "Portrait face photo of a smiling male with a double chin, bushy eyebrows, and head tilted slightly right.",
    "Portrait face photo of a smiling male with black hair, wearing glasses, and head facing slightly downward.",
    "Portrait face photo of a smiling male with a receding hairline, pale skin, and head turned slightly upward.",
    "Portrait face photo of a smiling male with a goatee, big lips, and head tilted slightly forward.",
    "Portrait face photo of a smiling male with arched eyebrows, wearing earrings, and head turned slightly to the left.",
    "Portrait face photo of a smiling male with an oval face, slight double chin, and head tilted slightly backward.",
    "Portrait face photo of a smiling male with brown hair, wearing lipstick, and head facing slightly upward.",
    "Portrait face photo of a smiling male with pale skin, bags under eyes, and head tilted slightly to the right.",
    "Portrait face photo of a smiling male with straight hair, rosy cheeks, and head turned slightly downward.",
    "Portrait face photo of a smiling male with chubby cheeks, wearing eyeglasses, and head facing slightly left.",
    "Portrait face photo of a smiling male with a goatee, narrow eyes, and head tilted slightly upward.",
    "Portrait face photo of a smiling male with a 5 o'clock shadow, bald, and head turned slightly to the right.",
    "Portrait face photo of a smiling male with big lips, wearing a necktie, and head tilted slightly forward.",
    "Portrait face photo of a smiling male with high cheekbones, wearing a hat, and head facing slightly downward.",
    "Portrait face photo of a smiling male with black hair, bushy eyebrows, and head turned slightly left.",
    "Portrait face photo of a smiling male with a moustache, wavy hair, and head tilted slightly to the left.",
    "Portrait face photo of a smiling male with an oval face, bags under eyes, and head facing slightly upward."
]
list_Smiling_Female = [
    "Portrait face photo of a smiling female with arched eyebrows, big lips, and head tilted slightly left.",
    "Portrait face photo of a smiling female with bangs, high cheekbones, and head turned slightly upward.",
    "Portrait face photo of a smiling female with black hair, wearing lipstick, and head facing downward.",
    "Portrait face photo of a smiling female with wavy hair, rosy cheeks, and head tilted slightly right.",
    "Portrait face photo of a smiling female with brown hair, oval face, and head turned slightly to the right.",
    "Portrait face photo of a smiling female with grey hair, heavy makeup, and head facing slightly upward.",
    "Portrait face photo of a smiling female with bushy eyebrows, wearing earrings, and head turned slightly left.",
    "Portrait face photo of a smiling female with big nose, chubby cheeks, and head facing slightly downward.",
    "Portrait face photo of a smiling female with straight hair, wearing eyeglasses, and head tilted slightly backward.",
    "Portrait face photo of a smiling female with arched eyebrows, bags under eyes, and head slightly tilted to the right.",
    "Portrait face photo of a smiling female with big lips, wearing a hat, and head turned slightly left.",
    "Portrait face photo of a smiling female with pale skin, high cheekbones, and head facing slightly downward.",
    "Portrait face photo of a smiling female with brown hair, pointy nose, and head tilted slightly to the left.",
    "Portrait face photo of a smiling female with wavy hair, wearing a necklace, and head turned slightly upward.",
    "Portrait face photo of a smiling female with narrow eyes, arched eyebrows, and head tilted slightly forward.",
    "Portrait face photo of a smiling female with black hair, wearing lipstick, and head turned slightly right.",
    "Portrait face photo of a smiling female with rosy cheeks, wearing eyeglasses, and head tilted slightly downward.",
    "Portrait face photo of a smiling female with bangs, high cheekbones, and head facing slightly upward.",
    "Portrait face photo of a smiling female with brown hair, chubby face, and head tilted slightly to the right.",
    "Portrait face photo of a smiling female with black hair, wearing a necklace, and head turned slightly left.",
    "Portrait face photo of a smiling female with big nose, wearing earrings, and head tilted slightly forward.",
    "Portrait face photo of a smiling female with straight hair, wearing a necktie, and head turned slightly upward.",
    "Portrait face photo of a smiling female with bushy eyebrows, narrow eyes, and head tilted slightly left.",
    "Portrait face photo of a smiling female with oval face, heavy makeup, and head facing slightly downward.",
    "Portrait face photo of a smiling female with pale skin, wearing a hat, and head tilted slightly to the right.",
    "Portrait face photo of a smiling female with arched eyebrows, big lips, and head turned slightly downward.",
    "Portrait face photo of a smiling female with rosy cheeks, wearing eyeglasses, and head tilted slightly backward.",
    "Portrait face photo of a smiling female with black hair, wearing lipstick, and head facing slightly upward.",
    "Portrait face photo of a smiling female with wavy hair, high cheekbones, and head turned slightly to the right.",
    "Portrait face photo of a smiling female with bangs, bags under eyes, and head facing slightly downward.",
    "Portrait face photo of a smiling female with straight hair, wearing a necklace, and head tilted slightly forward.",
    "Portrait face photo of a smiling female with narrow eyes, big nose, and head turned slightly left.",
    "Portrait face photo of a smiling female with black hair, wearing earrings, and head tilted slightly to the left.",
    "Portrait face photo of a smiling female with pale skin, heavy makeup, and head facing slightly upward.",
    "Portrait face photo of a smiling female with oval face, rosy cheeks, and head tilted slightly right.",
    "Portrait face photo of a smiling female with brown hair, wearing eyeglasses, and head turned slightly downward.",
    "Portrait face photo of a smiling female with arched eyebrows, chubby cheeks, and head facing slightly upward.",
    "Portrait face photo of a smiling female with high cheekbones, wearing a necktie, and head turned slightly right.",
    "Portrait face photo of a smiling female with black hair, pointy nose, and head tilted slightly to the left.",
    "Portrait face photo of a smiling female with narrow eyes, big lips, and head facing slightly downward.",
    "Portrait face photo of a smiling female with straight hair, wearing lipstick, and head turned slightly upward.",
    "Portrait face photo of a smiling female with rosy cheeks, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of a smiling female with bangs, big lips, and head facing slightly left.",
    "Portrait face photo of a smiling female with brown hair, wearing a necklace, and head tilted slightly to the right.",
    "Portrait face photo of a smiling female with arched eyebrows, narrow eyes, and head turned slightly downward.",
    "Portrait face photo of a smiling female with big nose, wearing earrings, and head tilted slightly backward.",
    "Portrait face photo of a smiling female with black hair, heavy makeup, and head turned slightly to the right.",
    "Portrait face photo of a smiling female with high cheekbones, oval face, and head facing slightly upward.",
    "Portrait face photo of a smiling female with bushy eyebrows, wearing eyeglasses, and head tilted slightly left.",
    "Portrait face photo of a smiling female with pale skin, wearing a necktie, and head facing slightly downward."
]
list_NoSmiling_Male = [
    "Portrait face photo of a male not smiling, with a 5 o'clock shadow, high cheekbones, and head slightly tilted left.",
    "Portrait face photo of a male not smiling, with arched eyebrows, chubby cheeks, and head turned slightly upward.",
    "Portrait face photo of a male not smiling, with a receding hairline, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of a male not smiling, with big lips, narrow eyes, slight double chin, head tilted right.",
    "Portrait face photo of a male not smiling, with black hair, a goatee, and head turned slightly right.",
    "Portrait face photo of a male not smiling, with grey hair, an oval face, and head facing slightly upward.",
    "Portrait face photo of a male not smiling, with bushy eyebrows, bags under eyes, and head turned slightly left.",
    "Portrait face photo of a male not smiling, with brown hair, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of a male not smiling, with a moustache, high cheekbones, and head tilted slightly backward.",
    "Portrait face photo of a male not smiling, with a bald head, pointy nose, and head slightly turned to the right.",
    "Portrait face photo of a male not smiling, with a goatee, big nose, and head tilted slightly forward.",
    "Portrait face photo of a male not smiling, with wavy hair, wearing earrings, and head turned slightly left.",
    "Portrait face photo of a male not smiling, with a 5 o'clock shadow, arched eyebrows, and head turned to the right.",
    "Portrait face photo of a male not smiling, with a narrow nose, slight double chin, and head facing upward.",
    "Portrait face photo of a male not smiling, with big lips, wearing a hat, and head tilted slightly to the left.",
    "Portrait face photo of a male not smiling, with a chubby face, straight hair, and head turned slightly downward.",
    "Portrait face photo of a male not smiling, with a goatee, pale skin, and head tilted slightly right.",
    "Portrait face photo of a male not smiling, with bags under eyes, wearing a necktie, and head turned slightly upward.",
    "Portrait face photo of a male not smiling, with wavy hair, arched eyebrows, and head slightly tilted forward.",
    "Portrait face photo of a male not smiling, with a receding hairline, pointy nose, and head facing slightly downward.",
    "Portrait face photo of a male not smiling, with a big nose, wearing eyeglasses, and head tilted slightly left.",
    "Portrait face photo of a male not smiling, with grey hair, high cheekbones, and head turned slightly to the left.",
    "Portrait face photo of a male not smiling, with bushy eyebrows, wearing a hat, and head tilted slightly forward.",
    "Portrait face photo of a male not smiling, with chubby cheeks, oval face, and head turned slightly upward.",
    "Portrait face photo of a male not smiling, with a double chin, straight hair, and head facing slightly left.",
    "Portrait face photo of a male not smiling, with big lips, wearing earrings, and head tilted slightly backward.",
    "Portrait face photo of a male not smiling, with a moustache, bags under eyes, and head turned slightly to the right.",
    "Portrait face photo of a male not smiling, with black hair, wearing a necktie, and head facing downward.",
    "Portrait face photo of a male not smiling, with big nose, arched eyebrows, and head turned slightly left.",
    "Portrait face photo of a male not smiling, with wavy hair, wearing lipstick, and head tilted slightly right.",
    "Portrait face photo of a male not smiling, with bushy eyebrows, pale skin, and head turned slightly upward.",
    "Portrait face photo of a male not smiling, with brown hair, high cheekbones, and head tilted slightly downward.",
    "Portrait face photo of a male not smiling, with arched eyebrows, wearing a hat, and head turned slightly left.",
    "Portrait face photo of a male not smiling, with a double chin, bushy eyebrows, and head tilted slightly right.",
    "Portrait face photo of a male not smiling, with black hair, wearing glasses, and head facing slightly downward.",
    "Portrait face photo of a male not smiling, with a receding hairline, pale skin, and head turned slightly upward.",
    "Portrait face photo of a male not smiling, with a goatee, big lips, and head tilted slightly forward.",
    "Portrait face photo of a male not smiling, with arched eyebrows, wearing earrings, and head turned slightly to the left.",
    "Portrait face photo of a male not smiling, with an oval face, slight double chin, and head tilted slightly backward.",
    "Portrait face photo of a male not smiling, with brown hair, wearing lipstick, and head facing slightly upward.",
    "Portrait face photo of a male not smiling, with pale skin, bags under eyes, and head tilted slightly to the right.",
    "Portrait face photo of a male not smiling, with straight hair, rosy cheeks, and head turned slightly downward.",
    "Portrait face photo of a male not smiling, with chubby cheeks, wearing eyeglasses, and head facing slightly left.",
    "Portrait face photo of a male not smiling, with a goatee, narrow eyes, and head tilted slightly upward.",
    "Portrait face photo of a male not smiling, with a 5 o'clock shadow, bald, and head turned slightly to the right.",
    "Portrait face photo of a male not smiling, with big lips, wearing a necktie, and head tilted slightly forward.",
    "Portrait face photo of a male not smiling, with high cheekbones, wearing a hat, and head facing slightly downward.",
    "Portrait face photo of a male not smiling, with black hair, bushy eyebrows, and head turned slightly left.",
    "Portrait face photo of a male not smiling, with a moustache, wavy hair, and head tilted slightly to the left.",
    "Portrait face photo of a male not smiling, with an oval face, bags under eyes, and head facing slightly upward."
]
list_NoSmiling_Female = [
    "Portrait face photo of a female not smiling, with arched eyebrows, high cheekbones, and head slightly tilted left.",
    "Portrait face photo of a female not smiling, with bangs, big nose, and head turned slightly upward.",
    "Portrait face photo of a female not smiling, with grey hair, wearing eyeglasses, and head facing downward.",
    "Portrait face photo of a female not smiling, with black hair, narrow eyes, slight double chin, head tilted right.",
    "Portrait face photo of a female not smiling, with rosy cheeks, wearing a hat, and head turned slightly right.",
    "Portrait face photo of a female not smiling, with bushy eyebrows, high cheekbones, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with wavy hair, pale skin, and head turned slightly left.",
    "Portrait face photo of a female not smiling, with big lips, wearing a necktie, and head facing slightly downward.",
    "Portrait face photo of a female not smiling, with straight hair, chubby cheeks, and head tilted slightly backward.",
    "Portrait face photo of a female not smiling, with brown hair, arched eyebrows, and head slightly tilted to the right.",
    "Portrait face photo of a female not smiling, with big nose, wearing earrings, and head turned slightly left.",
    "Portrait face photo of a female not smiling, with oval face, bags under eyes, and head facing slightly downward.",
    "Portrait face photo of a female not smiling, with straight hair, wearing a necklace, and head tilted slightly to the left.",
    "Portrait face photo of a female not smiling, with arched eyebrows, rosy cheeks, and head turned slightly upward.",
    "Portrait face photo of a female not smiling, with brown hair, narrow eyes, and head tilted slightly forward.",
    "Portrait face photo of a female not smiling, with pale skin, high cheekbones, and head turned slightly right.",
    "Portrait face photo of a female not smiling, with big lips, wearing lipstick, and head facing slightly downward.",
    "Portrait face photo of a female not smiling, with wavy hair, bags under eyes, and head tilted slightly right.",
    "Portrait face photo of a female not smiling, with bangs, oval face, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with straight hair, chubby face, and head tilted slightly to the left.",
    "Portrait face photo of a female not smiling, with black hair, wearing earrings, and head turned slightly downward.",
    "Portrait face photo of a female not smiling, with bushy eyebrows, wearing a necktie, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with narrow eyes, high cheekbones, and head tilted slightly forward.",
    "Portrait face photo of a female not smiling, with bangs, wearing a hat, and head turned slightly to the left.",
    "Portrait face photo of a female not smiling, with rosy cheeks, wearing eyeglasses, and head tilted slightly backward.",
    "Portrait face photo of a female not smiling, with black hair, pointy nose, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with brown hair, bags under eyes, and head turned slightly to the right.",
    "Portrait face photo of a female not smiling, with high cheekbones, wearing a necklace, and head facing slightly downward.",
    "Portrait face photo of a female not smiling, with bushy eyebrows, wearing earrings, and head tilted slightly left.",
    "Portrait face photo of a female not smiling, with chubby cheeks, pale skin, and head turned slightly downward.",
    "Portrait face photo of a female not smiling, with straight hair, wearing lipstick, and head tilted slightly forward.",
    "Portrait face photo of a female not smiling, with big lips, wearing a hat, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with narrow eyes, oval face, and head turned slightly to the left.",
    "Portrait face photo of a female not smiling, with arched eyebrows, bags under eyes, and head facing slightly downward.",
    "Portrait face photo of a female not smiling, with wavy hair, wearing a necktie, and head tilted slightly backward.",
    "Portrait face photo of a female not smiling, with big nose, rosy cheeks, and head turned slightly to the right.",
    "Portrait face photo of a female not smiling, with bangs, high cheekbones, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with black hair, oval face, and head tilted slightly to the left.",
    "Portrait face photo of a female not smiling, with pale skin, wearing lipstick, and head turned slightly downward.",
    "Portrait face photo of a female not smiling, with straight hair, wearing eyeglasses, and head facing slightly left.",
    "Portrait face photo of a female not smiling, with big lips, arched eyebrows, and head tilted slightly right.",
    "Portrait face photo of a female not smiling, with bushy eyebrows, wearing a hat, and head turned slightly forward.",
    "Portrait face photo of a female not smiling, with high cheekbones, wearing earrings, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with oval face, bags under eyes, and head tilted slightly backward.",
    "Portrait face photo of a female not smiling, with black hair, chubby cheeks, and head turned slightly to the left.",
    "Portrait face photo of a female not smiling, with bangs, wearing eyeglasses, and head tilted slightly downward.",
    "Portrait face photo of a female not smiling, with big nose, rosy cheeks, and head facing slightly upward.",
    "Portrait face photo of a female not smiling, with straight hair, wearing a necktie, and head turned slightly right.",
    "Portrait face photo of a female not smiling, with arched eyebrows, high cheekbones, and head tilted slightly left.",
    "Portrait face photo of a female not smiling, with brown hair, wearing earrings, and head facing slightly downward."
]