# V1
list_Female_White = [
    "Face photo of a 1-year-old White female with a curious expression and soft, fine baby hair.",
    "Face photo of a 3-year-old White female with a joyful smile, light curly pigtails, and freckles.",
    "Face photo of a 5-year-old White female with a serious expression and straight, short blonde hair.",
    "Face photo of a 7-year-old White female with a cheeky grin and wavy, medium-length brunette hair.",
    "Face photo of a 9-year-old White female with a pensive look and braided blonde hair with blue ribbons.",
    "Face photo of an 11-year-old White female with a bright smile and curly red hair, wearing glasses.",
    "Face photo of a 13-year-old White female with a thoughtful expression and straight brown hair with a headband.",
    "Face photo of a 15-year-old White female with a laughing face and wavy blonde hair with pink streaks.",
    "Face photo of a 17-year-old White female with a confident smirk and short pixie cut dyed purple.",
    "Face photo of a 19-year-old White female with a subtle smile and long straight black hair.",
    "Face photo of a 21-year-old White female with a flirty wink and curly blonde hair, wearing a red beret.",
    "Face photo of a 23-year-old White female with a serious face and a bob cut with bangs, brunette hair.",
    "Face photo of a 25-year-old White female with a joyful expression and long wavy red hair.",
    "Face photo of a 27-year-old White female with a sultry look and short curly brown hair.",
    "Face photo of a 29-year-old White female with a friendly smile and medium-length blonde hair tied in a bun.",
    "Face photo of a 31-year-old White female with a calm expression and long straight brunette hair.",
    "Face photo of a 33-year-old White female with a surprised look and short wavy blonde hair.",
    "Face photo of a 35-year-old White female with a relaxed smile and shoulder-length curly red hair.",
    "Face photo of a 37-year-old White female with an intense stare and straight black hair with gray strands.",
    "Face photo of a 39-year-old White female with a gentle expression and long wavy brunette hair with highlights.",
    "Face photo of a 41-year-old White female with a playful grin and short blonde bob.",
    "Face photo of a 43-year-old White female with a pensive expression and medium-length straight red hair.",
    "Face photo of a 45-year-old White female with a warm smile and long curly black hair.",
    "Face photo of a 47-year-old White female with an amused expression and short wavy blonde hair.",
    "Face photo of a 49-year-old White female with a serious face and long straight brunette hair.",
    "Face photo of a 51-year-old White female with a joyful laugh and medium-length curly grey hair.",
    "Face photo of a 53-year-old White female with a contemplative look and short red hair.",
    "Face photo of a 55-year-old White female with a confident smile and shoulder-length straight blonde hair.",
    "Face photo of a 57-year-old White female with an elegant expression and wavy brunette hair with silver streaks.",
    "Face photo of a 59-year-old White female with a relaxed face and short curly blonde hair.",
    "Face photo of a 61-year-old White female with a gentle smile and long straight grey hair.",
    "Face photo of a 63-year-old White female with a surprised expression and medium-length wavy red hair.",
    "Face photo of a 65-year-old White female with a thoughtful face and short curly white hair.",
    "Face photo of a 67-year-old White female with a lively smile and shoulder-length straight brunette hair.",
    "Face photo of a 69-year-old White female with a calm expression and long wavy silver hair.",
    "Face photo of a 71-year-old White female with a friendly grin and short curly grey hair.",
    "Face photo of a 73-year-old White female with an intense stare and medium-length straight white hair.",
    "Face photo of a 75-year-old White female with a serene smile and shoulder-length wavy grey hair.",
    "Face photo of a 77-year-old White female with a mischievous wink and short straight blonde hair.",
    "Face photo of a 79-year-old White female with a wise expression and long curly silver hair.",
    "Face photo of an 81-year-old White female with a cheerful laugh and medium-length wavy grey hair.",
    "Face photo of an 83-year-old White female with a hopeful face and short curly white hair.",
    "Face photo of an 85-year-old White female with a dignified expression and long straight silver hair.",
    "Face photo of an 87-year-old White female with a warm, inviting smile and shoulder-length curly grey hair.",
    "Face photo of an 89-year-old White female with a pensive look and short wavy blonde hair.",
    "Face photo of a 91-year-old White female with a joyful expression and medium-length straight white hair.",
    "Face photo of a 93-year-old White female with a relaxed demeanor and long curly grey hair.",
    "Face photo of a 95-year-old White female with an elegant smile and short straight silver hair.",
    "Face photo of a 97-year-old White female with a wise face and shoulder-length wavy grey hair.",
    "Face photo of a 99-year-old White female with a gentle expression and long straight white hair."
]
list_Female_NonWhite = [
    "Face photo of a 1-year-old Hispanic female with a bright smile and fine, dark wispy hair.",
    "Face photo of a 3-year-old Black female with twinkling eyes and tiny, natural curls.",
    "Face photo of a 5-year-old South Asian female with a curious expression and smooth, straight black hair.",
    "Face photo of a 7-year-old Southeast Asian female with a laughing face and short, bobbed hair.",
    "Face photo of a 9-year-old Middle Eastern female with a serious look and long, wavy brown hair.",
    "Face photo of an 11-year-old Hispanic female with a playful grin and shoulder-length curly hair.",
    "Face photo of a 13-year-old Black female with a thoughtful expression and braided hair with colorful beads.",
    "Face photo of a 15-year-old South Asian female with a joyful laugh and long, thick braids.",
    "Face photo of a 17-year-old Southeast Asian female with a confident smirk and a sleek ponytail.",
    "Face photo of a 19-year-old Middle Eastern female with a subtle smile and flowing, curly hair.",
    "Face photo of a 21-year-old Hispanic female with a flirty wink and voluminous, curly hair accessorized with flowers.",
    "Face photo of a 23-year-old Black female with an intense stare and short, natural afro.",
    "Face photo of a 25-year-old South Asian female with a calm expression and long, straight hair parted in the middle.",
    "Face photo of a 27-year-old Southeast Asian female with a warm, inviting smile and medium-length layered hair.",
    "Face photo of a 29-year-old Middle Eastern female with an elegant look and a tight, high bun adorned with gold clips.",
    "Face photo of a 31-year-old Hispanic female with a lively expression and long, wavy hair with sun-kissed highlights.",
    "Face photo of a 33-year-old Black female with a serene look and shoulder-length twists.",
    "Face photo of a 35-year-old South Asian female with a wide, beaming smile and thick, curly hair.",
    "Face photo of a 37-year-old Southeast Asian female with an amused expression and a stylish bob cut.",
    "Face photo of a 39-year-old Middle Eastern female with a contemplative stare and long, straight black hair.",
    "Face photo of a 41-year-old Hispanic female with a gentle smile and short, curly hair with silver strands.",
    "Face photo of a 43-year-old Black female with a fierce look and a regal afro puff.",
    "Face photo of a 45-year-old South Asian female with a joyful expression and long, wavy hair draped over her shoulders.",
    "Face photo of a 47-year-old Southeast Asian female with a shy smile and a neat, tucked bun.",
    "Face photo of a 49-year-old Middle Eastern female with a confident face and voluminous, shoulder-length curls.",
    "Face photo of a 51-year-old Hispanic female with a knowing laugh and medium-length hair with graceful waves.",
    "Face photo of a 53-year-old Black female with a wise expression and elegant locs.",
    "Face photo of a 55-year-old South Asian female with a reserved smile and a traditional bun with jasmine flowers.",
    "Face photo of a 57-year-old Southeast Asian female with an intense gaze and a sleek, long ponytail.",
    "Face photo of a 59-year-old Middle Eastern female with a pensive look and a layered cut with natural grey highlights.",
    "Face photo of a 61-year-old Hispanic female with a relaxed demeanor and long, flowing grey hair.",
    "Face photo of a 63-year-old Black female with a proud smile and a beautifully wrapped headscarf.",
    "Face photo of a 65-year-old South Asian female with a content expression and short, curly white hair.",
    "Face photo of a 67-year-old Southeast Asian female with a bright, engaging smile and a soft bob.",
    "Face photo of a 69-year-old Middle Eastern female with a reflective look and long, wavy grey hair.",
    "Face photo of a 71-year-old Hispanic female with a welcoming grin and medium-length, curly hair.",
    "Face photo of a 73-year-old Black female with a commanding stare and a crown of silver braids.",
    "Face photo of a 75-year-old South Asian female with a serene expression and glossy, long black hair with silver streaks.",
    "Face photo of a 77-year-old Southeast Asian female with a mischievous wink and short, playful curls.",
    "Face photo of a 79-year-old Middle Eastern female with a wise and gentle expression and shoulder-length silver hair.",
    "Face photo of an 81-year-old Hispanic female with a cheerful laugh and voluminous, wavy grey hair.",
    "Face photo of an 83-year-old Black female with a hopeful face and a chic, short afro.",
    "Face photo of an 85-year-old South Asian female with a dignified look and long, straight white hair.",
    "Face photo of an 87-year-old Southeast Asian female with a warm, maternal smile and medium-length curly hair.",
    "Face photo of an 89-year-old Middle Eastern female with a reflective expression and a stylish headscarf encircling her hair.",
    "Face photo of a 91-year-old Hispanic female with a joyful expression and a soft, fluffy white bob.",
    "Face photo of a 93-year-old Black female with a relaxed demeanor and elegant silver twists.",
    "Face photo of a 95-year-old South Asian female with a nostalgic smile and a classic bun adorned with pearls.",
    "Face photo of a 97-year-old Southeast Asian female with a graceful look and long, flowing white hair.",
    "Face photo of a 99-year-old Middle Eastern female with a noble expression and luscious, grey curls."
]
list_Male_White = [
    "Face photo of a 1-year-old White male with a joyful expression and soft, fine blond hair.",
    "Face photo of a 3-year-old White male with a curious gaze and messy, light brown hair.",
    "Face photo of a 5-year-old White male with a mischievous grin and short, curly red hair.",
    "Face photo of a 7-year-old White male with a serious look and straight, dark blonde hair.",
    "Face photo of a 9-year-old White male with a bright smile and medium-length brown hair.",
    "Face photo of an 11-year-old White male with an amused expression and a stylish, spiky haircut.",
    "Face photo of a 13-year-old White male with a pensive stare and long, wavy blonde hair.",
    "Face photo of a 15-year-old White male with a confident smirk and short, slicked-back hair.",
    "Face photo of a 17-year-old White male with a thoughtful expression and tousled, dirty blonde hair.",
    "Face photo of a 19-year-old White male with a relaxed smile and a neat buzz cut.",
    "Face photo of a 21-year-old White male with a flirty wink and medium-length curly hair.",
    "Face photo of a 23-year-old White male with an intense focus and short, straight dark hair.",
    "Face photo of a 25-year-old White male with a joyful laugh and long, flowing locks.",
    "Face photo of a 27-year-old White male with a sultry look and a modern pompadour hairstyle.",
    "Face photo of a 29-year-old White male with a gentle expression and short, wavy hair.",
    "Face photo of a 31-year-old White male with a stern face and closely cropped hair with subtle greying.",
    "Face photo of a 33-year-old White male with a wide grin and shoulder-length blonde hair.",
    "Face photo of a 35-year-old White male with a surprised expression and a high and tight military cut.",
    "Face photo of a 37-year-old White male with a relaxed demeanor and medium-length brunette hair.",
    "Face photo of a 39-year-old White male with a brooding look and a slick, undercut hairstyle.",
    "Face photo of a 41-year-old White male with a playful smile and messy, light brown hair.",
    "Face photo of a 43-year-old White male with a contemplative expression and short, curly grey hair.",
    "Face photo of a 45-year-old White male with a warm smile and a salt-and-pepper beard.",
    "Face photo of a 47-year-old White male with an intense glare and a shaved head.",
    "Face photo of a 49-year-old White male with a confident face and a neatly trimmed full beard.",
    "Face photo of a 51-year-old White male with a joyful chuckle and medium-length hair with distinguished grey streaks.",
    "Face photo of a 53-year-old White male with a wise expression and long, thinning hair.",
    "Face photo of a 55-year-old White male with a content smile and a classic side-part haircut.",
    "Face photo of a 57-year-old White male with a sophisticated look and a full, groomed grey beard.",
    "Face photo of a 59-year-old White male with a stern visage and short, grizzled hair.",
    "Face photo of a 61-year-old White male with a friendly grin and a balding crown with light hair on the sides.",
    "Face photo of a 63-year-old White male with an inquisitive look and a thick, white mustache.",
    "Face photo of a 65-year-old White male with a relaxed expression and a full head of silver hair.",
    "Face photo of a 67-year-old White male with a hearty laugh and medium-length, curly grey hair.",
    "Face photo of a 69-year-old White male with a contemplative stare and a neatly trimmed white beard.",
    "Face photo of a 71-year-old White male with a welcoming smile and a bald scalp with a fringe of white hair.",
    "Face photo of a 73-year-old White male with an earnest look and short, wispy white hair.",
    "Face photo of a 75-year-old White male with a calm expression and a distinguished, groomed beard.",
    "Face photo of a 77-year-old White male with a wise gaze and a fully bald head, sporting a neat mustache.",
    "Face photo of a 79-year-old White male with a nostalgic smile and thin, sparse white hair.",
    "Face photo of an 81-year-old White male with a serene look and a dense, snowy beard.",
    "Face photo of an 83-year-old White male with a lively expression and a slicked-back hairstyle of grey hair.",
    "Face photo of an 85-year-old White male with a dignified expression and a clean-shaven face.",
    "Face photo of an 87-year-old White male with a gentle grin and a classic flat cap over sparse grey hair.",
    "Face photo of an 89-year-old White male with a reflective expression and a full white beard.",
    "Face photo of a 91-year-old White male with a contented smile and short, neatly combed white hair.",
    "Face photo of a 93-year-old White male with a relaxed demeanor and a tidy, silver goatee.",
    "Face photo of a 95-year-old White male with an elegant smile and a well-groomed, thick white beard.",
    "Face photo of a 97-year-old White male with a wise face and a smooth, bald head.",
    "Face photo of a 99-year-old White male with a serene expression and a delicate white mustache."
]
list_Male_NonWhite = [
    "Face photo of a 1-year-old Black male with a bright smile and tiny, soft curls.",
    "Face photo of a 3-year-old Hispanic male with a curious look and short, wavy hair.",
    "Face photo of a 5-year-old South Asian male with a playful expression and a neat bowl cut.",
    "Face photo of a 7-year-old Middle Eastern male with a serious expression and thick, dark hair.",
    "Face photo of a 9-year-old Southeast Asian male with a cheeky grin and messy, spiked hair.",
    "Face photo of an 11-year-old Black male with a thoughtful look and cornrows adorned with beads.",
    "Face photo of a 13-year-old Hispanic male with a sly smirk and gelled back hair.",
    "Face photo of a 15-year-old South Asian male with a studious expression and a tidy side part.",
    "Face photo of a 17-year-old Middle Eastern male with a confident smile and a stylish fade haircut.",
    "Face photo of a 19-year-old Southeast Asian male with a gentle expression and long, flowing locks.",
    "Face photo of a 21-year-old Black male with a bright laugh and a high-top fade.",
    "Face photo of a 23-year-old Hispanic male with an intense gaze and slicked, short hair.",
    "Face photo of a 25-year-old South Asian male with a calm demeanor and curly, shoulder-length hair.",
    "Face photo of a 27-year-old Middle Eastern male with a warm smile and a full beard.",
    "Face photo of a 29-year-old Southeast Asian male with a pensive look and short, textured hair.",
    "Face photo of a 31-year-old Black male with a friendly grin and dreadlocks tied back.",
    "Face photo of a 33-year-old Hispanic male with a relaxed expression and a buzz cut.",
    "Face photo of a 35-year-old South Asian male with a surprised look and a thick mustache.",
    "Face photo of a 37-year-old Middle Eastern male with a confident smirk and medium-length wavy hair.",
    "Face photo of a 39-year-old Southeast Asian male with an amused expression and a comb over.",
    "Face photo of a 41-year-old Black male with a reflective gaze and neatly trimmed hair.",
    "Face photo of a 43-year-old Hispanic male with a stern look and a salt-and-pepper goatee.",
    "Face photo of a 45-year-old South Asian male with a beaming smile and a full beard.",
    "Face photo of a 47-year-old Middle Eastern male with an intense focus and a shaved head.",
    "Face photo of a 49-year-old Southeast Asian male with a relaxed demeanor and a thinning hairline.",
    "Face photo of a 51-year-old Black male with a gentle smile and short, grey hair.",
    "Face photo of a 53-year-old Hispanic male with a wise expression and long, greying hair pulled back.",
    "Face photo of a 55-year-old South Asian male with a joyful laugh and a neatly trimmed beard.",
    "Face photo of a 57-year-old Middle Eastern male with a contemplative stare and a lush, white beard.",
    "Face photo of a 59-year-old Southeast Asian male with a proud expression and a bald scalp.",
    "Face photo of a 61-year-old Black male with a welcoming grin and a clean-shaven head.",
    "Face photo of a 63-year-old Hispanic male with a hopeful look and short, curly white hair.",
    "Face photo of a 65-year-old South Asian male with a dignified expression and a salt-and-pepper mustache.",
    "Face photo of a 67-year-old Middle Eastern male with a hearty laugh and a full, groomed beard.",
    "Face photo of a 69-year-old Southeast Asian male with a reflective gaze and sparse, grey hair.",
    "Face photo of a 71-year-old Black male with a serene smile and a shiny bald head.",
    "Face photo of a 73-year-old Hispanic male with an earnest expression and a white goatee.",
    "Face photo of a 75-year-old South Asian male with a wise look and a thick, white beard.",
    "Face photo of a 77-year-old Middle Eastern male with a gentle grin and short, curly grey hair.",
    "Face photo of a 79-year-old Southeast Asian male with an intense stare and a smooth, clean-shaven face.",
    "Face photo of an 81-year-old Black male with a cheerful expression and a distinguished grey afro.",
    "Face photo of an 83-year-old Hispanic male with a calm demeanor and a neatly styled hair comb-over.",
    "Face photo of an 85-year-old South Asian male with a noble expression and a turban covering his hair.",
    "Face photo of an 87-year-old Middle Eastern male with a warm, inviting smile and a luxuriant white beard.",
    "Face photo of an 89-year-old Southeast Asian male with a pensive look and sparse, white hair.",
    "Face photo of a 91-year-old Black male with a contented smile and a classic flat cap over neatly combed hair.",
    "Face photo of a 93-year-old Hispanic male with a relaxed demeanor and elegant silver hair brushed back.",
    "Face photo of a 95-year-old South Asian male with an elegant smile and a well-groomed, thick white beard.",
    "Face photo of a 97-year-old Middle Eastern male with a wise face and a smooth, bald head.",
    "Face photo of a 99-year-old Southeast Asian male with a serene expression and a delicate white mustache."
]

# V2
# list_Female_White = [
#     "Portrait face photo of a 1-year-old White Female with bright blue eyes, a toothless grin, and wispy blonde hair adorned with a small bow.",
#     "Portrait face photo of a 3-year-old White Female with a playful expression, rosy cheeks, and short brown pigtails.",
#     "Portrait face photo of a 5-year-old White Female laughing cheerfully, freckles across her nose, and shoulder-length auburn hair.",
#     "Portrait face photo of a 7-year-old White Female with a shy smile, green eyes, and straight light brown hair clipped to the side.",
#     "Portrait face photo of a 9-year-old White Female grinning widely, wearing glasses, and curly red hair pulled back in a ponytail.",
#     "Portrait face photo of an 11-year-old White Female with a thoughtful expression, long straight black hair, and a light sprinkling of freckles.",
#     "Portrait face photo of a 13-year-old White Female with braces, a confident smile, and shoulder-length wavy blonde hair.",
#     "Portrait face photo of a 15-year-old White Female with a relaxed smile, hazel eyes, and short pixie-cut brown hair.",
#     "Portrait face photo of a 17-year-old White Female with an expressive gaze, high cheekbones, and long straight auburn hair.",
#     "Portrait face photo of a 19-year-old White Female with a joyful laugh, sun-kissed skin, and curly blonde hair flowing over her shoulders.",
#     "Portrait face photo of a 21-year-old White Female with a friendly smile, blue eyes, and a neat bob haircut.",
#     "Portrait face photo of a 23-year-old White Female with a contemplative expression, wavy red hair, and subtle makeup.",
#     "Portrait face photo of a 25-year-old White Female with a radiant smile, dark brown eyes, and long straight black hair.",
#     "Portrait face photo of a 27-year-old White Female with an energetic grin, freckles, and shoulder-length blonde hair tied back.",
#     "Portrait face photo of a 29-year-old White Female with an elegant demeanor, green eyes, and a stylish short haircut.",
#     "Portrait face photo of a 31-year-old White Female with a warm smile, curly brown hair, and wearing subtle earrings.",
#     "Portrait face photo of a 33-year-old White Female with a confident expression, red lipstick, and sleek straight hair.",
#     "Portrait face photo of a 35-year-old White Female laughing heartily, light wrinkles around her eyes, and wavy auburn hair.",
#     "Portrait face photo of a 37-year-old White Female with a serene expression, dark blonde hair in a loose updo.",
#     "Portrait face photo of a 39-year-old White Female with expressive eyes, a slight smile, and shoulder-length brown hair.",
#     "Portrait face photo of a 41-year-old White Female with a friendly grin, light freckles, and straight black hair.",
#     "Portrait face photo of a 43-year-old White Female with a thoughtful gaze, wavy blonde hair, and minimal makeup.",
#     "Portrait face photo of a 45-year-old White Female smiling warmly, green eyes, and curly red hair.",
#     "Portrait face photo of a 47-year-old White Female with an engaging smile, short brown hair, and glasses.",
#     "Portrait face photo of a 49-year-old White Female with a gentle expression, silver streaks in her hair, and light wrinkles.",
#     "Portrait face photo of a 51-year-old White Female with a confident smile, shoulder-length blonde hair, and wearing earrings.",
#     "Portrait face photo of a 53-year-old White Female with a contented expression, grey eyes, and short wavy hair.",
#     "Portrait face photo of a 55-year-old White Female with a cheerful laugh, crow's feet around her eyes, and curly auburn hair.",
#     "Portrait face photo of a 57-year-old White Female with a serene smile, silver hair pulled back neatly.",
#     "Portrait face photo of a 59-year-old White Female with a thoughtful expression, glasses, and short grey hair.",
#     "Portrait face photo of a 61-year-old White Female with a kind smile, blue eyes, and wavy silver hair.",
#     "Portrait face photo of a 63-year-old White Female with an energetic grin, laugh lines, and short blonde hair.",
#     "Portrait face photo of a 65-year-old White Female with a gentle smile, curly grey hair, and wearing subtle jewelry.",
#     "Portrait face photo of a 67-year-old White Female with a bright expression, silver hair styled elegantly.",
#     "Portrait face photo of a 69-year-old White Female with a peaceful gaze, long grey hair, and minimal makeup.",
#     "Portrait face photo of a 71-year-old White Female with a warm smile, light wrinkles, and short curly hair.",
#     "Portrait face photo of a 73-year-old White Female with a friendly expression, glasses, and wavy silver hair.",
#     "Portrait face photo of a 75-year-old White Female laughing heartily, crow's feet around her eyes, and short grey hair.",
#     "Portrait face photo of a 77-year-old White Female with a serene smile, white hair pulled back neatly.",
#     "Portrait face photo of a 79-year-old White Female with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of an 81-year-old White Female with a gentle smile, blue eyes, and short white hair.",
#     "Portrait face photo of an 83-year-old White Female with a cheerful expression, laugh lines, and wavy grey hair.",
#     "Portrait face photo of an 85-year-old White Female with a kind smile, silver hair, and wearing a small necklace.",
#     "Portrait face photo of an 87-year-old White Female with a peaceful gaze, white hair styled elegantly.",
#     "Portrait face photo of an 89-year-old White Female with a warm expression, light wrinkles, and short curly grey hair.",
#     "Portrait face photo of a 91-year-old White Female with a friendly smile, glasses, and wavy silver hair.",
#     "Portrait face photo of a 93-year-old White Female with a serene expression, white hair pulled back neatly.",
#     "Portrait face photo of a 95-year-old White Female with a joyful laugh, crow's feet around her eyes, and short white hair.",
#     "Portrait face photo of a 97-year-old White Female with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of a 99-year-old White Female with a gentle smile, blue eyes, and wavy white hair."
# ]
# list_Female_NonWhite = [
#     "Portrait face photo of a 1-year-old Asian Female with bright almond-shaped eyes, a toothless smile, and fine black hair adorned with a tiny bow.",
#     "Portrait face photo of a 3-year-old African Female with a joyful expression, chubby cheeks, and short curly hair decorated with colorful beads.",
#     "Portrait face photo of a 5-year-old Latina Female laughing happily, dimples on her cheeks, and long wavy brown hair tied in pigtails.",
#     "Portrait face photo of a 7-year-old Middle Eastern Female with a shy smile, dark eyes, and shoulder-length black hair clipped to the side.",
#     "Portrait face photo of a 9-year-old Native American Female grinning widely, high cheekbones, and straight dark brown hair braided neatly.",
#     "Portrait face photo of an 11-year-old South Asian Female with a thoughtful expression, long straight black hair, and a light sprinkling of freckles.",
#     "Portrait face photo of a 13-year-old Pacific Islander Female with braces, a confident smile, and shoulder-length wavy black hair.",
#     "Portrait face photo of a 15-year-old East Asian Female with a relaxed smile, hazel eyes, and a short bob haircut with side-swept bangs.",
#     "Portrait face photo of a 17-year-old African Female with an expressive gaze, smooth dark skin, and long braided hair adorned with beads.",
#     "Portrait face photo of a 19-year-old Latina Female with a joyful laugh, sun-kissed skin, and curly dark brown hair cascading over her shoulders.",
#     "Portrait face photo of a 21-year-old Middle Eastern Female with a friendly smile, brown eyes, and a hijab elegantly wrapped.",
#     "Portrait face photo of a 23-year-old South Asian Female with a contemplative expression, wavy black hair, and subtle makeup.",
#     "Portrait face photo of a 25-year-old East Asian Female with a radiant smile, dark brown eyes, and long straight black hair.",
#     "Portrait face photo of a 27-year-old African Female with an energetic grin, freckles, and shoulder-length natural curls.",
#     "Portrait face photo of a 29-year-old Latina Female with an elegant demeanor, green eyes, and a stylish short haircut.",
#     "Portrait face photo of a 31-year-old Native American Female with a warm smile, long straight black hair, and wearing subtle earrings.",
#     "Portrait face photo of a 33-year-old Middle Eastern Female with a confident expression, red lipstick, and sleek straight hair.",
#     "Portrait face photo of a 35-year-old South Asian Female laughing heartily, light wrinkles around her eyes, and wavy dark brown hair.",
#     "Portrait face photo of a 37-year-old East Asian Female with a serene expression, dark hair in a loose updo.",
#     "Portrait face photo of a 39-year-old African Female with expressive eyes, a slight smile, and shoulder-length braided hair.",
#     "Portrait face photo of a 41-year-old Latina Female with a friendly grin, light freckles, and straight dark brown hair.",
#     "Portrait face photo of a 43-year-old Middle Eastern Female with a thoughtful gaze, wavy black hair, and minimal makeup.",
#     "Portrait face photo of a 45-year-old Native American Female smiling warmly, brown eyes, and long braided hair.",
#     "Portrait face photo of a 47-year-old South Asian Female with an engaging smile, short black hair, and glasses.",
#     "Portrait face photo of a 49-year-old East Asian Female with a gentle expression, silver streaks in her hair, and light wrinkles.",
#     "Portrait face photo of a 51-year-old African Female with a confident smile, shoulder-length natural hair, and wearing earrings.",
#     "Portrait face photo of a 53-year-old Latina Female with a contented expression, hazel eyes, and short wavy hair.",
#     "Portrait face photo of a 55-year-old Middle Eastern Female with a cheerful laugh, crow's feet around her eyes, and curly black hair.",
#     "Portrait face photo of a 57-year-old South Asian Female with a serene smile, silver hair pulled back neatly.",
#     "Portrait face photo of a 59-year-old East Asian Female with a thoughtful expression, glasses, and short grey hair.",
#     "Portrait face photo of a 61-year-old African Female with a kind smile, dark eyes, and wavy silver hair.",
#     "Portrait face photo of a 63-year-old Latina Female with an energetic grin, laugh lines, and short dark brown hair.",
#     "Portrait face photo of a 65-year-old Native American Female with a gentle smile, long grey hair, and wearing subtle jewelry.",
#     "Portrait face photo of a 67-year-old Middle Eastern Female with a bright expression, silver hair styled elegantly.",
#     "Portrait face photo of a 69-year-old South Asian Female with a peaceful gaze, long grey hair, and minimal makeup.",
#     "Portrait face photo of a 71-year-old East Asian Female with a warm smile, light wrinkles, and short curly hair.",
#     "Portrait face photo of a 73-year-old African Female with a friendly expression, glasses, and wavy silver hair.",
#     "Portrait face photo of a 75-year-old Latina Female laughing heartily, crow's feet around her eyes, and short grey hair.",
#     "Portrait face photo of a 77-year-old Middle Eastern Female with a serene smile, white hair pulled back neatly.",
#     "Portrait face photo of a 79-year-old South Asian Female with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of an 81-year-old East Asian Female with a gentle smile, brown eyes, and short white hair.",
#     "Portrait face photo of an 83-year-old African Female with a cheerful expression, laugh lines, and wavy grey hair.",
#     "Portrait face photo of an 85-year-old Latina Female with a kind smile, silver hair, and wearing a small necklace.",
#     "Portrait face photo of an 87-year-old Middle Eastern Female with a peaceful gaze, white hair styled elegantly.",
#     "Portrait face photo of an 89-year-old South Asian Female with a warm expression, light wrinkles, and short curly grey hair.",
#     "Portrait face photo of a 91-year-old East Asian Female with a friendly smile, glasses, and wavy silver hair.",
#     "Portrait face photo of a 93-year-old African Female with a serene expression, white hair pulled back neatly.",
#     "Portrait face photo of a 95-year-old Native American Female with a joyful laugh, crow's feet around her eyes, and long white hair.",
#     "Portrait face photo of a 97-year-old Latina Female with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of a 99-year-old Middle Eastern Female with a gentle smile, brown eyes, and wavy white hair."
# ]
# list_Male_White = [
#     "Portrait face photo of a 1-year-old White Male with bright blue eyes, a toothless smile, and soft blonde hair.",
#     "Portrait face photo of a 3-year-old White Male with a playful grin, freckles across his cheeks, and short brown hair.",
#     "Portrait face photo of a 5-year-old White Male laughing cheerfully, rosy cheeks, and messy auburn hair.",
#     "Portrait face photo of a 7-year-old White Male with a shy smile, green eyes, and straight light brown hair.",
#     "Portrait face photo of a 9-year-old White Male grinning widely, wearing glasses, and curly red hair.",
#     "Portrait face photo of an 11-year-old White Male with a thoughtful expression, short black hair, and a light sprinkling of freckles.",
#     "Portrait face photo of a 13-year-old White Male with braces, a confident smile, and shaggy blonde hair.",
#     "Portrait face photo of a 15-year-old White Male with a relaxed smile, hazel eyes, and a short brown haircut.",
#     "Portrait face photo of a 17-year-old White Male with an expressive gaze, high cheekbones, and tousled auburn hair.",
#     "Portrait face photo of a 19-year-old White Male with a joyful laugh, sun-kissed skin, and curly blonde hair.",
#     "Portrait face photo of a 21-year-old White Male with a friendly smile, blue eyes, and a neat undercut hairstyle.",
#     "Portrait face photo of a 23-year-old White Male with a contemplative expression, wavy red hair, and subtle stubble.",
#     "Portrait face photo of a 25-year-old White Male with a radiant smile, dark brown eyes, and short black hair.",
#     "Portrait face photo of a 27-year-old White Male with an energetic grin, freckles, and slicked-back blonde hair.",
#     "Portrait face photo of a 29-year-old White Male with an elegant demeanor, green eyes, and a stylish short beard.",
#     "Portrait face photo of a 31-year-old White Male with a warm smile, curly brown hair, and wearing a subtle earring.",
#     "Portrait face photo of a 33-year-old White Male with a confident expression, clean-shaven, and sleek straight hair.",
#     "Portrait face photo of a 35-year-old White Male laughing heartily, light wrinkles around his eyes, and wavy auburn hair.",
#     "Portrait face photo of a 37-year-old White Male with a serene expression, dark blonde hair neatly combed.",
#     "Portrait face photo of a 39-year-old White Male with expressive eyes, a slight smile, and short brown hair.",
#     "Portrait face photo of a 41-year-old White Male with a friendly grin, light freckles, and short black hair.",
#     "Portrait face photo of a 43-year-old White Male with a thoughtful gaze, wavy blonde hair, and a neatly trimmed beard.",
#     "Portrait face photo of a 45-year-old White Male smiling warmly, green eyes, and curly red hair.",
#     "Portrait face photo of a 47-year-old White Male with an engaging smile, short brown hair, and glasses.",
#     "Portrait face photo of a 49-year-old White Male with a gentle expression, silver streaks in his hair, and light wrinkles.",
#     "Portrait face photo of a 51-year-old White Male with a confident smile, greying blonde hair, and a neatly trimmed mustache.",
#     "Portrait face photo of a 53-year-old White Male with a contented expression, grey eyes, and short wavy hair.",
#     "Portrait face photo of a 55-year-old White Male with a cheerful laugh, crow's feet around his eyes, and curly auburn hair.",
#     "Portrait face photo of a 57-year-old White Male with a serene smile, silver hair slicked back neatly.",
#     "Portrait face photo of a 59-year-old White Male with a thoughtful expression, glasses, and short grey hair.",
#     "Portrait face photo of a 61-year-old White Male with a kind smile, blue eyes, and wavy silver hair.",
#     "Portrait face photo of a 63-year-old White Male with an energetic grin, laugh lines, and short blonde hair.",
#     "Portrait face photo of a 65-year-old White Male with a gentle smile, curly grey hair, and wearing a subtle necklace.",
#     "Portrait face photo of a 67-year-old White Male with a bright expression, silver hair styled elegantly.",
#     "Portrait face photo of a 69-year-old White Male with a peaceful gaze, long grey hair tied back, and a full beard.",
#     "Portrait face photo of a 71-year-old White Male with a warm smile, light wrinkles, and short curly hair.",
#     "Portrait face photo of a 73-year-old White Male with a friendly expression, glasses, and wavy silver hair.",
#     "Portrait face photo of a 75-year-old White Male laughing heartily, crow's feet around his eyes, and short grey hair.",
#     "Portrait face photo of a 77-year-old White Male with a serene smile, white hair pulled back neatly.",
#     "Portrait face photo of a 79-year-old White Male with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of an 81-year-old White Male with a gentle smile, blue eyes, and short white hair.",
#     "Portrait face photo of an 83-year-old White Male with a cheerful expression, laugh lines, and wavy grey hair.",
#     "Portrait face photo of an 85-year-old White Male with a kind smile, silver hair, and wearing a small pendant.",
#     "Portrait face photo of an 87-year-old White Male with a peaceful gaze, white hair styled elegantly.",
#     "Portrait face photo of an 89-year-old White Male with a warm expression, light wrinkles, and short curly grey hair.",
#     "Portrait face photo of a 91-year-old White Male with a friendly smile, glasses, and wavy silver hair.",
#     "Portrait face photo of a 93-year-old White Male with a serene expression, white hair pulled back neatly.",
#     "Portrait face photo of a 95-year-old White Male with a joyful laugh, crow's feet around his eyes, and short white hair.",
#     "Portrait face photo of a 97-year-old White Male with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of a 99-year-old White Male with a gentle smile, blue eyes, and wavy white hair."
# ]
# list_Male_NonWhite = [
#     "Portrait face photo of a 1-year-old Asian Male with bright almond-shaped eyes, a toothless smile, and fine black hair.",
#     "Portrait face photo of a 3-year-old African Male with a playful grin, chubby cheeks, and short curly hair.",
#     "Portrait face photo of a 5-year-old Latino Male laughing cheerfully, dimples on his cheeks, and wavy brown hair.",
#     "Portrait face photo of a 7-year-old Middle Eastern Male with a shy smile, dark eyes, and short black hair.",
#     "Portrait face photo of a 9-year-old Native American Male grinning widely, high cheekbones, and straight dark brown hair.",
#     "Portrait face photo of an 11-year-old South Asian Male with a thoughtful expression, short black hair, and a light sprinkling of freckles.",
#     "Portrait face photo of a 13-year-old Pacific Islander Male with braces, a confident smile, and shaggy black hair.",
#     "Portrait face photo of a 15-year-old East Asian Male with a relaxed smile, hazel eyes, and a short spiky haircut.",
#     "Portrait face photo of a 17-year-old African Male with an expressive gaze, smooth dark skin, and short twisted hair.",
#     "Portrait face photo of a 19-year-old Latino Male with a joyful laugh, sun-kissed skin, and curly dark brown hair.",
#     "Portrait face photo of a 21-year-old Middle Eastern Male with a friendly smile, brown eyes, and a neatly trimmed beard.",
#     "Portrait face photo of a 23-year-old South Asian Male with a contemplative expression, wavy black hair, and subtle stubble.",
#     "Portrait face photo of a 25-year-old East Asian Male with a radiant smile, dark brown eyes, and short black hair.",
#     "Portrait face photo of a 27-year-old African Male with an energetic grin, freckles, and short dreadlocks.",
#     "Portrait face photo of a 29-year-old Latino Male with an elegant demeanor, green eyes, and a stylish short beard.",
#     "Portrait face photo of a 31-year-old Native American Male with a warm smile, long straight black hair, and wearing a subtle earring.",
#     "Portrait face photo of a 33-year-old Middle Eastern Male with a confident expression, clean-shaven, and slicked-back hair.",
#     "Portrait face photo of a 35-year-old South Asian Male laughing heartily, light wrinkles around his eyes, and wavy dark brown hair.",
#     "Portrait face photo of a 37-year-old East Asian Male with a serene expression, dark hair neatly combed.",
#     "Portrait face photo of a 39-year-old African Male with expressive eyes, a slight smile, and short curly hair.",
#     "Portrait face photo of a 41-year-old Latino Male with a friendly grin, light freckles, and short dark brown hair.",
#     "Portrait face photo of a 43-year-old Middle Eastern Male with a thoughtful gaze, wavy black hair, and a neatly trimmed beard.",
#     "Portrait face photo of a 45-year-old Native American Male smiling warmly, brown eyes, and long braided hair.",
#     "Portrait face photo of a 47-year-old South Asian Male with an engaging smile, short black hair, and glasses.",
#     "Portrait face photo of a 49-year-old East Asian Male with a gentle expression, silver streaks in his hair, and light wrinkles.",
#     "Portrait face photo of a 51-year-old African Male with a confident smile, greying hair, and a neatly trimmed mustache.",
#     "Portrait face photo of a 53-year-old Latino Male with a contented expression, hazel eyes, and short wavy hair.",
#     "Portrait face photo of a 55-year-old Middle Eastern Male with a cheerful laugh, crow's feet around his eyes, and curly black hair.",
#     "Portrait face photo of a 57-year-old South Asian Male with a serene smile, silver hair slicked back neatly.",
#     "Portrait face photo of a 59-year-old East Asian Male with a thoughtful expression, glasses, and short grey hair.",
#     "Portrait face photo of a 61-year-old African Male with a kind smile, dark eyes, and wavy silver hair.",
#     "Portrait face photo of a 63-year-old Latino Male with an energetic grin, laugh lines, and short dark brown hair.",
#     "Portrait face photo of a 65-year-old Native American Male with a gentle smile, long grey hair tied back, and wearing subtle jewelry.",
#     "Portrait face photo of a 67-year-old Middle Eastern Male with a bright expression, silver hair styled elegantly.",
#     "Portrait face photo of a 69-year-old South Asian Male with a peaceful gaze, long grey hair, and a full beard.",
#     "Portrait face photo of a 71-year-old East Asian Male with a warm smile, light wrinkles, and short curly hair.",
#     "Portrait face photo of a 73-year-old African Male with a friendly expression, glasses, and wavy silver hair.",
#     "Portrait face photo of a 75-year-old Latino Male laughing heartily, crow's feet around his eyes, and short grey hair.",
#     "Portrait face photo of a 77-year-old Middle Eastern Male with a serene smile, white hair pulled back neatly.",
#     "Portrait face photo of a 79-year-old South Asian Male with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of an 81-year-old East Asian Male with a gentle smile, brown eyes, and short white hair.",
#     "Portrait face photo of an 83-year-old African Male with a cheerful expression, laugh lines, and wavy grey hair.",
#     "Portrait face photo of an 85-year-old Latino Male with a kind smile, silver hair, and wearing a small pendant.",
#     "Portrait face photo of an 87-year-old Middle Eastern Male with a peaceful gaze, white hair styled elegantly.",
#     "Portrait face photo of an 89-year-old South Asian Male with a warm expression, light wrinkles, and short curly grey hair.",
#     "Portrait face photo of a 91-year-old East Asian Male with a friendly smile, glasses, and wavy silver hair.",
#     "Portrait face photo of a 93-year-old African Male with a serene expression, white hair pulled back neatly.",
#     "Portrait face photo of a 95-year-old Native American Male with a joyful laugh, crow's feet around his eyes, and long white hair.",
#     "Portrait face photo of a 97-year-old Latino Male with a thoughtful gaze, wearing glasses, and curly silver hair.",
#     "Portrait face photo of a 99-year-old Middle Eastern Male with a gentle smile, brown eyes, and wavy white hair."
# ]